services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduplacer
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eduplacer"]
      interval: 5s
      timeout: 5s
      retries: 12
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/eduplacer?schema=public"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      JWT_SECRET: "chut_ke_deewane"
      JWT_EXPIRY: "1d"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/app/:cached
    command: ["sh", "-c", ""] # entrypoint is used; keep blank
    tty: true

volumes:
  postgres-data:
